// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypfqjtaujcafoullwfvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwZnFqdGF1amNhZm91bGx3ZnZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM5MTI3NzYsImV4cCI6MjA3OTQ4ODc3Nn0.itkDZCoBcYY_B38aT-0-xgV4AnDnIjpVaS67Fcso4XA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});